default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME']%>
  password: <%= ENV['PASSWORD']%>
  host: <%= ENV['HOST']%>

development:
  <<: *default
  database: book_reviews_app_development

test:
  <<: *default
  database: book_reviews_app_test

production:
  <<: *default
  database: book_reviews_app_production
  username: book_reviews_app
  password: <%= ENV["BOOK_REVIEWS_APP_DATABASE_PASSWORD"] %>
